//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arche_Resume_Master
    {
        public decimal AR_Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Contact { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Skill { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Experience { get; set; }
        public Nullable<int> Notice { get; set; }
        public Nullable<double> CTC { get; set; }
        public string Resume { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
