//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATS2019_dbEntities : DbContext
    {
        public ATS2019_dbEntities()
            : base("name=ATS2019_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance_Master> Attendance_Master { get; set; }
        public virtual DbSet<Client_Master> Client_Master { get; set; }
        public virtual DbSet<DailyTarget_Master> DailyTarget_Master { get; set; }
        public virtual DbSet<HolidayList_Master> HolidayList_Master { get; set; }
        public virtual DbSet<Interview_Master> Interview_Master { get; set; }
        public virtual DbSet<Leave_Master> Leave_Master { get; set; }
        public virtual DbSet<NewClient_Master> NewClient_Master { get; set; }
        public virtual DbSet<Offer_Master> Offer_Master { get; set; }
        public virtual DbSet<Recruiter_SalarySlip_Master> Recruiter_SalarySlip_Master { get; set; }
        public virtual DbSet<Requirement_Master> Requirement_Master { get; set; }
        public virtual DbSet<Role_Master> Role_Master { get; set; }
        public virtual DbSet<SalesClient_Master> SalesClient_Master { get; set; }
        public virtual DbSet<SalesClientCall_Master> SalesClientCall_Master { get; set; }
        public virtual DbSet<SalesClientwiseMonthlyRevenue_Master> SalesClientwiseMonthlyRevenue_Master { get; set; }
        public virtual DbSet<SalesMonthlyReport_Master> SalesMonthlyReport_Master { get; set; }
        public virtual DbSet<Team_Master> Team_Master { get; set; }
        public virtual DbSet<User_Activity_Master> User_Activity_Master { get; set; }
        public virtual DbSet<User_Master> User_Master { get; set; }
        public virtual DbSet<Resume_Master> Resume_Master { get; set; }
        public virtual DbSet<Arche_Resume_Master> Arche_Resume_Master { get; set; }
        public virtual DbSet<Reyna_SalarySlip_Master> Reyna_SalarySlip_Master { get; set; }
    }
}
