//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_Master
    {
        public decimal A_Id { get; set; }
        public string A_Name { get; set; }
        public Nullable<System.DateTime> A_InTime { get; set; }
        public string A_InIP { get; set; }
        public Nullable<System.DateTime> A_OutTime { get; set; }
        public string A_OutIP { get; set; }
        public string A_Time { get; set; }
    }
}
