//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Master
    {
        public decimal C_id { get; set; }
        public string C_Name { get; set; }
        public string C_Address { get; set; }
        public string C_Cont_Person1 { get; set; }
        public decimal C_Cont_Person1_No { get; set; }
        public string C_Cont_Person1_Email { get; set; }
        public string C_Cont_Person2 { get; set; }
        public Nullable<decimal> C_Cont_Person2_No { get; set; }
        public string C_Cont_Person2_Email { get; set; }
        public string C_Category { get; set; }
        public string C_Type { get; set; }
        public string C_Segment { get; set; }
        public string C_Margin_Type { get; set; }
        public Nullable<decimal> C_Margin { get; set; }
        public int C_Is_Active { get; set; }
        public int C_Is_Delete { get; set; }
        public Nullable<System.DateTime> C_Created_On { get; set; }
        public string C_Created_By { get; set; }
        public Nullable<System.DateTime> C_Updated_On { get; set; }
        public string C_Updated_By { get; set; }
    }
}
