//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTarget_Master
    {
        public decimal DT_Id { get; set; }
        public string DT_AssignTo { get; set; }
        public int DT_Target { get; set; }
        public int DT_Achived { get; set; }
        public Nullable<System.DateTime> DT_CreateOn { get; set; }
    }
}
