//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayList_Master
    {
        public decimal Hid { get; set; }
        public string Hname { get; set; }
        public string Hdate { get; set; }
        public string Hday { get; set; }
        public string Htype { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
