//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview_Master
    {
        public decimal I_Id { get; set; }
        public decimal I_RId { get; set; }
        public decimal I_JId { get; set; }
        public System.DateTime I_Date { get; set; }
        public string I_Time { get; set; }
        public string I_By { get; set; }
        public string I_Location { get; set; }
        public string I_Note { get; set; }
        public string I_Status { get; set; }
        public string I_CreateBy { get; set; }
        public System.DateTime I_CreateOn { get; set; }
    }
}
