//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Master
    {
        public decimal L_Id { get; set; }
        public string L_Type { get; set; }
        public double L_Noofdays { get; set; }
        public string L_Inwords { get; set; }
        public string L_Reason { get; set; }
        public System.DateTime L_StartDate { get; set; }
        public System.DateTime L_EndDate { get; set; }
        public string L_CreateBy { get; set; }
        public System.DateTime L_CreateOn { get; set; }
        public string L_TL_Status { get; set; }
        public Nullable<System.DateTime> L_TL_Datetime { get; set; }
        public string L_M_Status { get; set; }
        public Nullable<System.DateTime> L_M_Datetime { get; set; }
        public string L_Admin_Status { get; set; }
        public Nullable<System.DateTime> L_Admin_Datetime { get; set; }
    }
}
