//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewClient_Master
    {
        public decimal NId { get; set; }
        public string NClient { get; set; }
        public string NPoc { get; set; }
        public string NStatus { get; set; }
        public string NRemark1 { get; set; }
        public string NRemark2 { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
