//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer_Master
    {
        public decimal O_Id { get; set; }
        public decimal O_Iid { get; set; }
        public decimal O_Rid { get; set; }
        public decimal O_Jid { get; set; }
        public string O_Fullname { get; set; }
        public Nullable<System.DateTime> O_DOB { get; set; }
        public string O_Gender { get; set; }
        public string O_MaritalStatus { get; set; }
        public string O_Cur_Add { get; set; }
        public string O_Perm_Add { get; set; }
        public string O_Country { get; set; }
        public string O_Email { get; set; }
        public string O_Cur_Des { get; set; }
        public string O_Off_Des { get; set; }
        public string O_Skill { get; set; }
        public string O_Tot_Exp { get; set; }
        public string O_Rel_Exp { get; set; }
        public string O_Mobile { get; set; }
        public string O_Alt_Mobile { get; set; }
        public string O_Pan { get; set; }
        public string O_Client { get; set; }
        public string O_Location { get; set; }
        public Nullable<decimal> O_CTC { get; set; }
        public Nullable<decimal> O_ECTC { get; set; }
        public Nullable<decimal> O_BR { get; set; }
        public Nullable<decimal> O_PR { get; set; }
        public Nullable<decimal> O_GP { get; set; }
        public Nullable<decimal> O_GPM { get; set; }
        public Nullable<System.DateTime> O_Sel_Date { get; set; }
        public Nullable<System.DateTime> O_Off_Date { get; set; }
        public Nullable<System.DateTime> O_Join_Date { get; set; }
        public Nullable<System.DateTime> O_Exit_Date { get; set; }
        public string O_Emergency { get; set; }
        public string O_Account_No { get; set; }
        public string O_Bank_Name { get; set; }
        public string O_Branch { get; set; }
        public string O_IFCI { get; set; }
        public Nullable<decimal> O_Aadhar { get; set; }
        public string O_Status { get; set; }
        public string O_Note { get; set; }
        public string O_Type { get; set; }
        public string O_Recruiter { get; set; }
        public Nullable<System.DateTime> O_Recuiter_Date { get; set; }
        public string O_Teamlead { get; set; }
        public Nullable<System.DateTime> O_Teamlead_Date { get; set; }
        public string O_AM { get; set; }
        public Nullable<System.DateTime> O_AM_Date { get; set; }
        public string O_Manager_Status { get; set; }
        public Nullable<System.DateTime> O_Manager_Date { get; set; }
        public string O_Account_Status { get; set; }
        public Nullable<System.DateTime> O_Account_Date { get; set; }
        public string O_Admin_Status { get; set; }
        public Nullable<System.DateTime> O_Admin_Date { get; set; }
        public Nullable<int> O_IsActive { get; set; }
    }
}
