//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruiter_SalarySlip_Master
    {
        public decimal Salary_Id { get; set; }
        public Nullable<decimal> Employee_Code { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Pan { get; set; }
        public Nullable<decimal> CTC { get; set; }
        public Nullable<decimal> Basic_Salary { get; set; }
        public Nullable<decimal> Fixed_HRA { get; set; }
        public Nullable<decimal> Fixed_Conveyance_Allowance { get; set; }
        public Nullable<decimal> Fixed_Medical_Allowance { get; set; }
        public Nullable<decimal> Additional_HRA_Allowance { get; set; }
        public Nullable<decimal> Total_Days { get; set; }
        public Nullable<decimal> Paid_Leave { get; set; }
        public Nullable<decimal> LWP_Days { get; set; }
        public Nullable<decimal> Total_Payable_Days { get; set; }
        public Nullable<decimal> Gross_Salary_Payable { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> House_Rent { get; set; }
        public Nullable<decimal> Employer_Cont_To_PF { get; set; }
        public Nullable<decimal> Conveyance_Allowance { get; set; }
        public Nullable<decimal> Medical_Allowance { get; set; }
        public Nullable<decimal> Add_HRA_Allowance { get; set; }
        public Nullable<decimal> Flexible_Allowance { get; set; }
        public Nullable<decimal> Incentive_Allowance { get; set; }
        public Nullable<decimal> Total_Earning { get; set; }
        public Nullable<decimal> PF_Employer { get; set; }
        public Nullable<decimal> PF_Employee { get; set; }
        public Nullable<decimal> Esic_Employer { get; set; }
        public Nullable<decimal> Esic_Employee { get; set; }
        public Nullable<decimal> PT { get; set; }
        public Nullable<decimal> Advances { get; set; }
        public Nullable<decimal> Income_Tax { get; set; }
        public Nullable<decimal> Total_Deduction { get; set; }
        public Nullable<decimal> Net_Payable { get; set; }
        public string Salary_Month { get; set; }
        public string Salary_Year { get; set; }
    }
}
