//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Master
    {
        public decimal J_Id { get; set; }
        public string J_Code { get; set; }
        public decimal J_Client_Id { get; set; }
        public string J_Skill { get; set; }
        public int J_Position { get; set; }
        public string J_Location { get; set; }
        public string J_EndClient { get; set; }
        public string J_AssignUser { get; set; }
        public Nullable<double> J_Tot_Min_Exp { get; set; }
        public Nullable<double> J_Tot_Max_Exp { get; set; }
        public Nullable<double> J_Rel_Min_Exp { get; set; }
        public Nullable<double> J_Rel_Max_Exp { get; set; }
        public Nullable<decimal> J_Bill_Rate { get; set; }
        public Nullable<decimal> J_Pay_Rate { get; set; }
        public string J_Category { get; set; }
        public string J_Type { get; set; }
        public string J_Employment_Type { get; set; }
        public string J_POC { get; set; }
        public Nullable<decimal> J_POC_No { get; set; }
        public string J_JD { get; set; }
        public string J_Status { get; set; }
        public long J_Is_Active { get; set; }
        public long J_Is_Delete { get; set; }
        public string J_CreatedBy { get; set; }
        public Nullable<System.DateTime> J_CreatedOn { get; set; }
        public string J_UpdatedBy { get; set; }
        public Nullable<System.DateTime> J_UpdatedOn { get; set; }
        public string J_MandatorySkill { get; set; }
    }
}
