//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume_Master
    {
        public decimal R_Id { get; set; }
        public decimal R_Jid { get; set; }
        public string R_Name { get; set; }
        public Nullable<System.DateTime> R_DOB { get; set; }
        public string R_Address { get; set; }
        public string R_Cnt { get; set; }
        public string R_Alt_Cnt { get; set; }
        public string R_Email { get; set; }
        public string R_Tot_Exp { get; set; }
        public string R_Rel_Exp { get; set; }
        public string R_Cur_Com { get; set; }
        public string R_Cur_Des { get; set; }
        public string R_NP { get; set; }
        public string R_Canjoin { get; set; }
        public string R_Cur_CTC { get; set; }
        public string R_Exp_CTC { get; set; }
        public string R_Reason { get; set; }
        public string R_Any_Int_Of { get; set; }
        public string R_Education { get; set; }
        public string R_Cur_Location { get; set; }
        public string R_Pref_Location { get; set; }
        public string R_Native { get; set; }
        public string R_Resumename { get; set; }
        public string R_Status { get; set; }
        public string R_CreateBy { get; set; }
        public Nullable<System.DateTime> R_CreateOn { get; set; }
        public string R_Skills { get; set; }
        public string R_FamilyCnt { get; set; }
        public string R_friendcnt { get; set; }
        public string R_reasongap { get; set; }
        public string R_Currenttakehome { get; set; }
        public string R_Currentdrawing { get; set; }
        public string R_Lastsalaryhike { get; set; }
        public string R_Expectedtakehome { get; set; }
        public string R_Expecteddrawing { get; set; }
        public string R_HikeReason { get; set; }
        public string R_Howjoinearlyreason { get; set; }
        public string R_WhyJoinArche { get; set; }
        public string R_HaveDocs { get; set; }
        public string R_Reasonofrelocation { get; set; }
        public string R_Pannumber { get; set; }
        public string R_Telephonicinttiming { get; set; }
        public string R_F2Favailibility { get; set; }
        public string R_updateby { get; set; }
        public Nullable<System.DateTime> R_updateon { get; set; }
    }
}
