//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Master
    {
        public decimal R_id { get; set; }
        public decimal R_ecode { get; set; }
        public string R_role { get; set; }
    }
}
