//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMonthlyReport_Master
    {
        public decimal SMR_Id { get; set; }
        public string SMR_Month { get; set; }
        public string SMR_Year { get; set; }
        public int SMR_Client { get; set; }
        public int SMR_OpenPosition { get; set; }
        public int SMR_BusinessReceived { get; set; }
        public int SMR_Submission { get; set; }
        public int SMR_Int_received { get; set; }
        public int SMR_Feedback_Pending { get; set; }
        public int SMR_Noshow { get; set; }
        public int SMR_Offer { get; set; }
        public int SMR_BD { get; set; }
        public int SMR_Join { get; set; }
        public int SMR_PassThrough { get; set; }
        public int SMR_BulkDeal { get; set; }
        public int SMR_POExtended { get; set; }
        public int SMR_AttritionSaved { get; set; }
        public decimal SMR_TotalRevenue { get; set; }
        public string SMR_Remark { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
