//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesClientwiseMonthlyRevenue_Master
    {
        public decimal SRR_Id { get; set; }
        public string SRR_Month { get; set; }
        public decimal SRR_Year { get; set; }
        public decimal SRR_Client { get; set; }
        public Nullable<int> SRR_Current_HC { get; set; }
        public Nullable<decimal> SRR_Total_GP { get; set; }
        public Nullable<decimal> SRR_Avg_GP_Added { get; set; }
        public Nullable<int> SRR_Start { get; set; }
        public Nullable<int> SRR_Attrition { get; set; }
        public Nullable<int> SRR_BD { get; set; }
        public Nullable<int> SRR_Actual_Start { get; set; }
        public Nullable<decimal> SRR_Net_Total_GP { get; set; }
        public Nullable<decimal> SRR_Total_GP_Added { get; set; }
        public string SRR_Typeof_Employement { get; set; }
        public Nullable<System.DateTime> SRR_Create_On { get; set; }
        public string SRR_Create_By { get; set; }
        public Nullable<System.DateTime> SRR_Update_On { get; set; }
        public string SRR_Update_By { get; set; }
    }
}
