//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesClientCall_Master
    {
        public decimal scr_id { get; set; }
        public System.DateTime scr_date { get; set; }
        public string scr_client { get; set; }
        public string scr_poc { get; set; }
        public string scr_agenda { get; set; }
        public string scr_createdby { get; set; }
        public System.DateTime scr_creaton { get; set; }
    }
}
