//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team_Master
    {
        public decimal T_Id { get; set; }
        public string T_TeamLead { get; set; }
        public string T_TeamMember { get; set; }
        public string T_CreatedBy { get; set; }
        public Nullable<System.DateTime> T_CreatedOn { get; set; }
        public string T_UpdatedBy { get; set; }
        public Nullable<System.DateTime> T_UpdatedOn { get; set; }
    }
}
