//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS2019_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Master
    {
        public int E_Id { get; set; }
        public Nullable<decimal> E_Code { get; set; }
        public string E_Fullname { get; set; }
        public string E_Gender { get; set; }
        public string E_Email { get; set; }
        public Nullable<System.DateTime> E_DOB { get; set; }
        public Nullable<decimal> E_ContNo { get; set; }
        public Nullable<decimal> E_EEmergencyContNo { get; set; }
        public string E_UserName { get; set; }
        public string E_Password { get; set; }
        public string E_Address { get; set; }
        public string E_CAddress { get; set; }
        public Nullable<decimal> E_Postal { get; set; }
        public string E_Etype { get; set; }
        public string E_Company_Name { get; set; }
        public string E_Department { get; set; }
        public string E_Designation { get; set; }
        public string E_Location { get; set; }
        public Nullable<System.DateTime> E_OfferDate { get; set; }
        public Nullable<System.DateTime> E_JoinDate { get; set; }
        public Nullable<System.DateTime> E_ExitDate { get; set; }
        public string E_Role { get; set; }
        public string E_BloodGroup { get; set; }
        public string E_BankName { get; set; }
        public string E_AccountNo { get; set; }
        public string E_Branch { get; set; }
        public string E_IFC_Code { get; set; }
        public string E_PF_Account { get; set; }
        public string E_PAN_No { get; set; }
        public Nullable<decimal> E_Aadhar_no { get; set; }
        public Nullable<double> E_Salary { get; set; }
        public Nullable<double> E_PF { get; set; }
        public Nullable<double> E_PT { get; set; }
        public Nullable<double> E_ESI { get; set; }
        public Nullable<int> E_PF_Apply { get; set; }
        public Nullable<int> E_PT_Apply { get; set; }
        public Nullable<int> E_ESI_Apply { get; set; }
        public string E_Photo { get; set; }
        public Nullable<int> E_Is_Active { get; set; }
        public Nullable<int> E_Is_Delete { get; set; }
        public string E_Created_By { get; set; }
        public Nullable<System.DateTime> E_Created_On { get; set; }
        public string E_Updated_By { get; set; }
        public Nullable<System.DateTime> E_Updated_On { get; set; }
    }
}
